env:
  global:
  - AWS_REGION=eu-west-1
  - STATE_BUCKET=testype
  - BLUE_STATE_KEY=demotiad/frontblue
  - GREEN_STATE_KEY=demotiad/frontgreen
  - APP_DIR=app/vote
  - REPO_NAME=demotiad/vote
  - WEBSITE=front-alb-ecs-1794205304.eu-west-1.elb.amazonaws.com
  - TERRAFORM_VERSION=0.11.7
  - TOOLS_DIR=$HOME/tools
  - TERRAFORM_DIR=terraform/app/frontends
  - secure: KrAsCjuut2Kap8arhtQIF0cmRgWRI+6W5n8BgRedYqE/70SSFkmqNB9N7HpGvOMZhNkMhDFTFfnNqkQzjyZcxCLh7Jmc7pyGrfaVuwozLcAhDHOJaxeywke8GfCoC2yk/vvzpUPJml3nGuQie5wQ5k7U0rSxwbi5R/Rn1y2RwyVxwmzK90nv+BUzprCObJb3fR65PXmXhq/mYl6g1i9vk5vqdthM5mDsYOdX8cjMkf/hG8IXOPNRtTPnGCXJu6hVsJjLAZcYjl6r8SiizC25dxpspa2gqPNe6c+c+O+fyuC7fMXVGrqeqB8WQz9p9oZ+JBdupz6+9JBScOqTEk6gPDEa6/vt6enI9Ui8ZdcayItik4jjqEJSDv5cNC/wI+5UR5zcW6Ovn1IHUXYarWZKgw6hpf4Ns1esCwe0reoLSyfCPNm15h5YQnVS/v2P5yVf3IGVp3oykwz0XVzRQPCXT0UnnVAuTCHj7VLW3JLVW4vvFDF+1qi8bGkNBRsoghnsO8Cpi083doqcN/b2EdMd8A1vH1Niy6M2IMzEWam+uww35jiCBbROXwdsLL2ZyS7tUrSjn1mQmYRzD7y2nabOy/wWgQascfs7k1nKMZDgAWWnY9WS3TlzyT2lugQ/h3BSQiDmvJJMnxKXBtnTdp/F6vL9f2cCsloGE0mBiiH/pzo=
  - secure: T40/G0vH2JzSDPb72iCTWXguyk0//WkgaUL9URGHdgUy0Hh4Ys7FHEUC5HAA76JO0+fclmslTsj6QXUby1PnVp34DnW6zOrvYMRgqapeYNYO1p+/HfXV4QMR22e1T0kO6xd57nzvOkfm4592xch+sKtH9P47dNAJQGDKJdD20z+14LXCzW2uzg8cOMDSv5nVlGN8ziw4q99KnMp+SRdeD7YWPR8gv3wV06G2IIgq43Rt1z6qSwfVQp0I9UmdtwqrOnE2MJ7tT1X8IzF/gZLtufxmd8AGMzrpLyPlFNR1r9I3Jlqf0RU0os3asEkkPzL3f8HvvoJPOdMWvnyakuHSwz5SxPhVzZ80I3Ct16ljHObcl+v0x8Wcg2XY1W5eFKT3PnI2Dns2fEVRzVHtdwx2JcsVtn0hcoYldfeWsRfbNDnzFjbr4gXZSM4JvACsZgsPUREhAQrPl+dMA7bD2SM4b+IYDr/Ca+gG5hvOgCiPvNu/nImXPgGcJ6xHJHPU0TuDnZw5hO3rWfxXEnh6DuyNIdlq0tLWxYEjaY+uAKtPv9Rm7L12GYEwz9c1bmsNvn7aXn0/GW8JNZXpD3rJ/r6kd8jceIlaZ8rSXzgpeiEcy07cuEUG/BelnnFQwsH4sESpR+ingxkKe6up4uvok9/w8O7C8Nl+7JKK/+US730gHTk=
sudo: required
language: python
python:
- '2.7'
services:
- docker
script:
- export COMMIT_SUBJECT="$(git log --format=%s --no-merges -n 1)"
before_deploy:
- export PATH=$PATH:$TOOLS_DIR/bin
- scripts/install_terraform.sh
- pip install awscli
deploy:
  provider: script
  script:
  - scripts/build_push_update.sh
  on:
    branch: master
    condition: $COMMIT_SUBJECT != *"[no deploy]"*
